#!/usr/bin/env python3
"""把 metadata、摘要和关键词渲染到 chapters/basicinfo.tex。"""

from __future__ import annotations

import argparse
from pathlib import Path

from common import latex_escape, load_metadata_yaml, metadata_bool, metadata_value, now_iso, print_json, read_json, rel, safe_resolve_under, write_json


def list_or_text(value) -> str:
    if isinstance(value, list):
        return "；".join(str(item) for item in value)
    return "" if value is None else str(value)


def render(root: Path, metadata_path: Path, thesis_path: Path | None) -> dict:
    metadata = load_metadata_yaml(metadata_path)
    thesis = read_json(thesis_path, default={}) if thesis_path and thesis_path.exists() else {}
    thesis_meta = thesis.get("metadata", {})
    abstracts = thesis_meta.get("abstracts", {})
    keywords = thesis_meta.get("keywords", {})

    report_style = metadata_value(metadata, "report_style", default="0")
    has_subtitle = metadata_bool(metadata, "has_subtitle", default=False)
    title_cn = metadata_value(metadata, "thesis_title_cn", "title_cn", "title", default="")
    title_abs_cn = metadata_value(metadata, "thesis_title_abs_cn", "title_abs_cn", "thesisTitleAbs", default="")
    title_en = metadata_value(metadata, "thesis_title_en", "title_en", default="")
    subtitle_cn = metadata_value(metadata, "thesis_subtitle_cn", "subtitle_cn", default="")
    subtitle_en = metadata_value(metadata, "thesis_subtitle_en", "subtitle_en", default="")
    abstract_cn = thesis_meta.get("abstract_cn") or abstracts.get("cn") or abstracts.get("zh") or ""
    abstract_en = thesis_meta.get("abstract_en") or abstracts.get("en") or ""
    keywords_cn = thesis_meta.get("keywords_cn") or keywords.get("cn") or keywords.get("zh") or ""
    keywords_en = thesis_meta.get("keywords_en") or keywords.get("en") or ""

    lines = [
        "% Generated by zufe-thesis-typesetter. Edit metadata.yaml/thesis.json, then rerender.",
        "% 基本信息",
        f"\\newcommand{{\\reportStyle}}{{{latex_escape(report_style)}}}",
        "",
        f"\\newcommand{{\\thesisTitle}}{{{latex_escape(title_cn)}}}",
        *([f"\\newcommand{{\\thesisTitleAbs}}{{{latex_escape(title_abs_cn)}}}"] if title_abs_cn else []),
        f"\\newcommand{{\\thesisTitleEN}}{{{latex_escape(title_en)}}}",
        "",
        "\\haveSub{}" if has_subtitle else "% \\haveSub{}",
        f"\\newcommand{{\\thesisSubTitle}}{{{latex_escape(subtitle_cn)}}}",
        f"\\newcommand{{\\thesisSubTitleEN}}{{{latex_escape(subtitle_en)}}}",
        "",
        f"\\newcommand{{\\deptName}}{{{latex_escape(metadata_value(metadata, 'college', 'deptName', default=''))}}}",
        f"\\newcommand{{\\majorName}}{{{latex_escape(metadata_value(metadata, 'major', 'majorName', default=''))}}}",
        f"\\newcommand{{\\yourName}}{{{latex_escape(metadata_value(metadata, 'name', 'yourName', default=''))}}}",
        f"\\newcommand{{\\yourStudentID}}{{{latex_escape(metadata_value(metadata, 'student_id', 'studentID', default=''))}}}",
        f"\\newcommand{{\\mentorName}}{{{latex_escape(metadata_value(metadata, 'mentor', 'mentorName', default=''))}}}",
        f"\\newcommand{{\\className}}{{{latex_escape(metadata_value(metadata, 'class_name', 'className', default=''))}}}",
        f"\\newcommand{{\\Today}}{{{latex_escape(metadata_value(metadata, 'date', 'today', default=''))}}}",
        "",
        "% 中英文摘要与关键词",
        f"\\newcommand{{\\abstractCN}}{{{latex_escape(abstract_cn)}}}",
        "",
        f"\\newcommand{{\\keywordsCN}}{{{latex_escape(list_or_text(keywords_cn))}}}",
        "",
        f"\\newcommand{{\\abstractEN}}{{{latex_escape(abstract_en)}}}",
        "",
        f"\\newcommand{{\\keywordsEN}}{{{latex_escape(list_or_text(keywords_en))}}}",
        "",
    ]
    target = safe_resolve_under(root, "chapters/basicinfo.tex", "chapters")
    target.write_text("\n".join(lines), encoding="utf-8")

    if thesis_path and thesis_path.exists():
        thesis.setdefault("render_log", []).append(
            {
                "step": "render_basicinfo",
                "status": "completed",
                "target": rel(target, root),
                "rendered_at": now_iso(),
            }
        )
        for block in thesis.get("source_blocks", []):
            if block.get("target_slot") == "chapters/basicinfo.tex" and block.get("status") == "mapped":
                block["status"] = "rendered"
                block["render_result"] = {"path": "chapters/basicinfo.tex", "kind": "latex_macro"}
        write_json(thesis_path, thesis)

    return {
        "flow": "B",
        "step": "render_basicinfo",
        "status": "passed",
        "target": rel(target, root),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--metadata", default="workspace/input/metadata.yaml")
    parser.add_argument("--thesis-json", default="workspace/intermediate/thesis.json")
    args = parser.parse_args()
    root = Path(args.root).expanduser().resolve()
    metadata_path = (root / args.metadata).resolve() if not Path(args.metadata).is_absolute() else Path(args.metadata).resolve()
    thesis_path = (root / args.thesis_json).resolve() if not Path(args.thesis_json).is_absolute() else Path(args.thesis_json).resolve()
    result = render(root, metadata_path, thesis_path)
    print_json(result)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
